close(): fix exception and enable fast-close
adafruit/Adafruit_CircuitPython_Requests pull request #156
Opened 2024-02-28 07:13 UTC by bablokb

The current code throws an exception during `close()` when it tries to convert an empty buffer (`chunk_header`).
This PR also adds an optional parameter `fast=False`. Passing `True` will skip reading.

This addresses #130 (also mentioned in #138)

2024-02-29 18:15 UTC, tannewt commented
Let's not add it to `close()` because that changes it from the Requests API: https://requests.readthedocs.io/en/latest/api/#requests.Response.close

Instead, please add it as a kwarg on `Session()`. The `Session()` API already varies from CPython.

2024-02-29 18:15 UTC, tannewt requested changes
Please move kwarg to `fast_close` kwarg in `Session()`.

2024-03-01 11:45 UTC, bablokb commented
Maybe I am missing something, but this would imply that I

- add a kwarg to Session()
- the constructor saves this as a public property
- `Response.__init__()` will query the property from the Session-object passed to it and save it as an instance attribute
- `Response.close()` uses this instance attribute

This seems rather involved. In my solution, I added an optional argument to `Response.close()`, so as long as you don't use it, the code is compatible. And the whole `Response` class is not compatible after all, there are many differences already.

But probably the whole drain-the-buffer-code should not be here after all, but somewhere where the socket is actually closed. Until this is implemented, I see both of my changes as a workaround. Instead of changing the code in many places, it might be wiser to just remove the additional option and wait for the real solution.

2024-03-01 21:45 UTC, tannewt commented
> And the whole `Response` class is not compatible after all, there are many differences already.

What are these differences? The intent is that the same code will work with CPython's request.

> This seems rather involved.

It is a bit of plumbing but it isn't complex *and* it preserves the API. I'd have session pass it into the response object as a separate kwarg.

> In my solution, I added an optional argument to `Response.close()`, so as long as you don't use it, the code is compatible.

"so as long as you don't use it" is a big caveat. We shouldn't make it possible to write incompatible code so you don't need to worry about it or need to redo it later.

2024-03-02 11:03 UTC, bablokb commented
> What are these differences? The intent is that the same code will work with CPython's request.

e.g. the constructor of `Response` in CPython does not take any arguments.

> I'd have session pass it into the response object as a separate kwarg.

What is the fundamental difference between adding an additional kwarg to the `Response` constructor compared to adding a kwarg to `Response.close()`?

Anyhow, I will do what you suggested to get the fix for the chunk_size exception merged, that is the most important problem.

2024-03-04 18:08 UTC, tannewt commented
> > What are these differences? The intent is that the same code will work with CPython's request.
> 
> e.g. the constructor of `Response` in CPython does not take any arguments.
> 
> > I'd have session pass it into the response object as a separate kwarg.
> 
> What is the fundamental difference between adding an additional kwarg to the `Response` constructor compared to adding a kwarg to `Response.close()`?

Response objects aren't usually created by user code. Instead, they are constructed by the library internally and returned. To me, that makes the constructor more private than close.

> 
> Anyhow, I will do what you suggested to get the fix for the chunk_size exception merged, that is the most important problem.

Thanks!

2024-03-05 18:31 UTC, merged

2024-03-11 14:46 UTC, justmobilize commented
@bablokb what is your thought around `fast_close`? I understand the `chunk` bug fix, but don't fully understand this one.

2024-03-11 14:51 UTC, dhalbert commented
Is there a CPython `requests` equivalent to the `fast_close` functionality, or is there something different about our `requests` semantics?

2024-03-11 15:46 UTC, bablokb commented
> @bablokb what is your thought around `fast_close`? I understand the `chunk` bug fix, but don't fully understand this one.

There are streams that never end (e.g. internet radio mp3-streams). In this case reading the socket until it is empty will never succeed.

2024-03-11 16:09 UTC, dhalbert commented
I can revert the PR if it makes sense, or if you can just rebase and fix, @justmobilize, that's fine too.

2024-03-11 16:15 UTC, justmobilize commented
@dhalbert I should have my PR ready by Wednesday. I can do either:
1. include the `empty_chucks` and fix and not having close keep reading read
2. remove the `fast_close` and fix and not having close keep reading read
Up to you on what's best (revert now or wait)

2024-03-11 16:24 UTC, dhalbert commented
@justmobilize Do 2., so that we have at least one fix for now.

2024-03-11 16:25 UTC, justmobilize commented
Sounds good

2024-03-13 09:02 UTC, bablokb commented
Tested it with 9.0.0-rc0 and a Pico-W and it works fine.